### ISSUE TITLE
Migrazione dati da match3 a Ellipse

### ISSUE THREAD

**Issue by StebaKite** [StebaKite/ellipse#33]
1. Attraverso l'export da Match3 di query ad hoc e import di CSV in postgres
2. Per la tabelle più stabili inseriamo in Gthub i CSV ottenuti (nella cartella db), ci serviranno più volte
3. Se scrivi del codice a maggior ragione inseriamolo in Github

**Comment by mattia155** [comment]
Scusa Stefano, ma facendo del codice java dove lo devo inserire poi?
Le import le faccio in sql semplice da pgAdmin? 
C'è un pezzo di codice java non dovrebbe avere tanto di connettori al database e tutto?
(Adesso comunque appena ho finito di sistemare i dati che ho preso provo un po', magari poi risolvo subito :) )

**Comment by mattia155** [comment]
Magari sto dicendo una stronzata.... ma che senso ha "idCategoria" in "Listino" ? 
Visto che "Listino" contiene solo numerazione del listino, numerazione progressiva e nome listino
Un listino può contenere o meno tutte le categorie, ma non le conterrà lui stesso, saranno le voci listino ad appartenere alle categorie che così come saranno le voci listino ad appartenere ad uno dei tre listini

**Comment by mattia155** [comment]
Ho i dati sia con le chiavi numeriche progressive esportate, che senza, carico quelle senza che tanto, se non erro, avevam detto che le avrebbe assegnate progressivamente direttamente durante l'import
giusto?

**Comment by StebaKite** [comment]
E, pultroppo l'import non le genera.
l'unico modo per generare le pk (primary key) è attraverso le insert.
Puoi trasformare i file di dati che hai ottenuto in una sequenza di insert,
io ho fatto cosi nell'esempio
Il 08/gen/2015 00:12 "Mattia" <notifications@github.com> ha scritto:

**Comment by StebaKite** [comment]
Per quanto riguarda la colonna idcategoria credo di aver capito....
Al momento esiste la relazione fra categoria-listino ma probabilmente è errata (ecco perchè non riesci a dargli senso) ...dovremo eliminarla e creare la relazione categoria-voce

**Comment by StebaKite** [comment]
Ho aggiornato lo schema del db su Architect.
dal terminale posizionati su var/www/html/ellipse   e dai i comandi: 
-  git branch --list         (in verde deve essere la master)
- se non lo è dai:    git checkout master
- poi dai:   git pull https://github.com/StebaKite/ellipse.git

a questo punto puoi ricreare il database da pgadmin fai :
- drop del db di test
- ricrea il database vuoto "ellipse.test"
- aggiungi lo schema "paziente"
- apri architect dal terminale .....  java -jar architect
- apri il file che contiene il disegno del db -> Tools>Forward Engineer

**Comment by mattia155** [comment]
si ma non riesco ad aprire il nuovo disegno del database aggiornato da architect, mi da errore!!

**Comment by mattia155** [comment]
metto le insert per categoria e listino che dovrei ricordarmele a memoria, solo che le lascio un attimo solo su db per non sbagliare
