### ISSUE TITLE
Usare la sessione

### ISSUE THREAD

**Issue by StebaKite** [StebaKite/ellipse#57]
Passaggio dei dati nella sessione anzichè negli oggotti

**Comment by StebaKite** [comment]
Ho esteso l'uso della sessione a tutte le funzioni.

**Comment by marcoalfredo61** [comment]
Di che

 

 

Da: Stefano [mailto:notifications@github.com] 
Inviato: giovedì 5 marzo 2015 13.31
A: StebaKite/ellipse
Oggetto: Re: [ellipse] Usare la sessione (#57)

 

Ho esteso l'uso della sessione a tutte le funzioni.

—
Reply to this email directly or view it on GitHub <https://github.com/StebaKite/ellipse/issues/57#issuecomment-77355915> .Immagine rimossa dal mittente.

Nessun virus nel messaggio.
Controllato da AVG - www.avg.com
Versione: 2015.0.5751 / Database dei virus: 4299/9232 - Data di rilascio: 05/03/2015




-----
Nessun virus nel messaggio.
Controllato da AVG - www.avg.com
Versione: 2015.0.5751 / Database dei virus: 4299/9232 -  Data di rilascio: 05/03/2015
